### PR TITLE
Release/0.3.0

### PR DESCRIPTION
**Pull request by lpulidoa**
Both "Feature branches" information file and "Hotfix branches" information file have been added :3

### CODE REVIEW

**Review by angegonzalez — APPROVED** [review]
LGTM!

**Review by JCastilloRC — APPROVED** [review]

**Comment by jsaenz-endava** [comment]
Guys, please remove the footnotes of all the product section pages and include them in a separate README.md file, where you can add a link to the main page of your product (the great tutorial you're building).

**Comment by angegonzalez** [comment]
Suggested changes included in the last commit!
Thanks!

**Review by jsaenz-endava — APPROVED** [review]
Neat!

**Comment by jsaenz-endava** [comment]
Please proceed with the merge and tag :)

**Pull request merged**
